// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJNt9l4MWMOKMUNWpZt288Sm86e4TogGM',
    appId: '1:548942434577:web:4716bccaffe71e7fa37cb0',
    messagingSenderId: '548942434577',
    projectId: 'fasummmm-e06ed',
    authDomain: 'fasummmm-e06ed.firebaseapp.com',
    databaseURL: 'https://fasummmm-e06ed-default-rtdb.firebaseio.com',
    storageBucket: 'fasummmm-e06ed.firebasestorage.app',
    measurementId: 'G-VX5EYN3HXR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBISpQ2Y7HE21N1h80oosbWiWTzkQsPgSA',
    appId: '1:548942434577:android:749fdd4aaac401dba37cb0',
    messagingSenderId: '548942434577',
    projectId: 'fasummmm-e06ed',
    databaseURL: 'https://fasummmm-e06ed-default-rtdb.firebaseio.com',
    storageBucket: 'fasummmm-e06ed.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJNt9l4MWMOKMUNWpZt288Sm86e4TogGM',
    appId: '1:548942434577:web:672ab15f4fd4b4b9a37cb0',
    messagingSenderId: '548942434577',
    projectId: 'fasummmm-e06ed',
    authDomain: 'fasummmm-e06ed.firebaseapp.com',
    databaseURL: 'https://fasummmm-e06ed-default-rtdb.firebaseio.com',
    storageBucket: 'fasummmm-e06ed.firebasestorage.app',
    measurementId: 'G-MENZZM37PH',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpgRYxLBaNhhCq2TOF8JBkA4v_dFoO_Sk',
    appId: '1:548942434577:ios:52fde380ae2a707da37cb0',
    messagingSenderId: '548942434577',
    projectId: 'fasummmm-e06ed',
    databaseURL: 'https://fasummmm-e06ed-default-rtdb.firebaseio.com',
    storageBucket: 'fasummmm-e06ed.firebasestorage.app',
    iosClientId:
        '548942434577-msvl5n5gv46igo69o4aoiqivt508jiqb.apps.googleusercontent.com',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpgRYxLBaNhhCq2TOF8JBkA4v_dFoO_Sk',
    appId: '1:548942434577:ios:52fde380ae2a707da37cb0',
    messagingSenderId: '548942434577',
    projectId: 'fasummmm-e06ed',
    databaseURL: 'https://fasummmm-e06ed-default-rtdb.firebaseio.com',
    storageBucket: 'fasummmm-e06ed.firebasestorage.app',
    iosClientId:
        '548942434577-msvl5n5gv46igo69o4aoiqivt508jiqb.apps.googleusercontent.com',
    iosBundleId: 'com.example.fasum',
  );
}
